### ISSUE TITLE
Error running tokenizer

### ISSUE THREAD

**Issue by fkgruber** [xinyu-dev/TransMHCII#1]
tokenizer = T5Tokenizer.from_pretrained("../prot_t5_xl_uniref50", do_lower_case=False)

Traceback (most recent call last):
  File "<string>", line 17, in __PYTHON_EL_eval
  File "<string>", line 1, in <module>
  File "/Users/user/miniconda3/envs/pytorch2/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1813, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
                                    ^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/pytorch2/lib/python3.11/site-packages/transformers/utils/hub.py", line 428, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/Users/user/miniconda3/envs/pytorch2/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/Users/user/miniconda3/envs/pytorch2/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 164, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '../prot_t5_xl_uniref50'.
>>>

**Comment by fkgruber** [comment]
I just realized that T5Tokenizer downloads the data transformer directly.
